default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci


development:
  <<: *default
  database: dpa_development
  pool: 5
  username: <%= ENV['DB_ENV_DB_USER'] %>
  password: <%= ENV['DB_ENV_DB_PASS'] %>
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>

test:
  <<: *default
  database: dpa_test
  pool: 5
  username: <%= ENV['DB_ENV_DB_USER'] %>
  password: <%= ENV['DB_ENV_DB_PASS'] %>
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>


